name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: use node 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm ci
    - run: npm run lint
    - run: npm run compile
    - run: npm test
    - name: Publish to staging
      run: npm run publish:nodes
      env:
        NODESCRIPT_API_URL: https://hub.staging.nodescript.dev
        NODESCRIPT_API_USERNAME: inca
        NODESCRIPT_API_TOKEN: ${{ secrets.NODESCRIPT_API_TOKEN_STAGING }}
        NODESCRIPT_WORKSPACE_ID: ERED9uHPQ3Fuxz97
    - name: Publish to production
      run: npm run publish:nodes
      env:
        NODESCRIPT_API_URL: https://hub.nodescript.dev
        NODESCRIPT_API_USERNAME: inca
        NODESCRIPT_API_TOKEN: ${{ secrets.NODESCRIPT_API_TOKEN_PRODUCTION }}
        NODESCRIPT_WORKSPACE_ID: 1EbcWpqLBDxtKkqS
